### PR TITLE
Update pci-dss-attestation-of-compliance.njk

### PR DESCRIPTION
**Pull request by alanmaddrell**
update reference to PCI to 4.0

### CODE REVIEW

**Review by richblake — APPROVED** [review]
I spoke with Kat and she said that I can approve simple changes to the tech docs and product pages. So approving this. Thanks Alan, you can now merge it.

**Comment by alanmaddrell** [comment]
> I spoke with Kat and she said that I can approve simple changes to the tech docs and product pages. So approving this. Thanks Alan, you can now merge it.

Apparently it needs an approving review as some tests are failing. Will Slack so engineers can have a look

**Review by richblake — APPROVED** [review]
Trying an approving comment again

**Review by jfharden — APPROVED** [review]

**Comment by jfharden** [comment]
This change has been merged in https://github.com/alphagov/pay-selfservice/pull/4257

**Pull request closed without merging**
