### PR TITLE
Replace apostrophe → ' ← with right single quotation mark → ’ ←

### PR DESCRIPTION
**Pull request by alexbishop1**
Change:

“It's quick and easy to create a payment link and you don’t need any technical knowledge.”

… to:

“It’s quick and easy to create a payment link and you don’t need any technical knowledge.”

### CODE REVIEW

**Comment by jonheslop** [comment]
👏 the ' is called a prime and the latter is an apostrophe ’

**Comment by jonheslop** [comment]
you can get a proper ’ with `shift+alt+[`

**Comment by alexbishop1** [comment]
I was using the names that Unicode assigns to them:

0027 ' APOSTROPHE — https://www.unicode.org/charts/PDF/U2000.pdf
2019 ’ RIGHT SINGLE QUOTATION MARK — https://www.unicode.org/charts/PDF/U0000.pdf

It’s `Shift`+`Alt`+`]` to get a ’ on a British English Mac keyboard (`Shift`+`Alt`+`[` is ”).

**Comment by jonheslop** [comment]
Oops yeah i meant the other bracket.

And that’s outrageous that unicode call the first thing an apostrophe

**Comment by alexbishop1** [comment]
I suspect the name was inherited from ASCII or something.

**Pull request merged**
