### PR TITLE
PP-4583 - Remove unused tunnel, hogan and readdir packages

### PR DESCRIPTION
**Pull request by 46bit**
## WHAT
The tunnel `npm` package is not imported anywhere in `pay-selfservice`. If this PR goes green it may be worth removing.

## HOW 
Do you know why tunnel is there? If not, do you know who might know?

### CODE REVIEW

**Comment by rhowe-gds** [comment]
Don't you need to regenerate `package-lock.json` via `npm install`?

**Comment by rhowe-gds** [comment]
It was removed in commit f1977e50db162d198052758b5c5f5349057db0a9 just over a year ago

**Comment by rhowe-gds** [comment]
Looks like `hogan.js` can go as well after we stopped using it in commit 6077de5d17673ad59358bfe9f965fd3bc089dfb1 @jonheslop ?

**Comment by jonheslop** [comment]
> Looks like `hogan.js` and `readdir` can go as well after we stopped using them in commit [6077de5](https://github.com/alphagov/pay-selfservice/commit/6077de5d17673ad59358bfe9f965fd3bc089dfb1) @jonheslop ?

😱 yes deffo, and yeah package-lock.json should be regenerated too

**Comment by 46bit** [comment]
thanks! 😄

**Pull request merged**
