### PR TITLE
PP-6333 Add Node Debug launch file and clean up code

### PR DESCRIPTION
**Pull request by iqbalgds**
- Add debug launch.json file
- Clean up start.js file

### CODE REVIEW

**Comment by sfount** [comment]
This to clarify that this changes the entry file that self service uses in the production environment and so should be reviewed/ released very carefully. 

I have paired/ reviewed the changes and can't see any major downsides to removing the multiple thread handling per process; we already scale services based on containers so shouldn't need this additional layer of load balancing. Self services isn't required to serve many connections at once and likely never even uses the additional threads capacity.

To clarify this change has also been made as multiple threads has interfered with attaching a debugger to the Node process however isn't required for this work as a separate script could be used for development. 

The only consideration from me is if the log lines that have been removed are used in any monitoring tools however they aren't as far as I'm aware.

**Comment by iqbalgds** [comment]
The Node multi-threading in Node was done using Throng:
https://github.com/alphagov/pay-frontend/pull/1483
This library has not been updated for 4 years and it not that popular in Github.
This was blocking us from debugging our node apps.
Therefore, this library and relevant code was removed from the `start.js`.
This should also have an added benefit of making the Node apps start up quicker.

**Comment by iqbalgds** [comment]
Agreed - called the file `start-dev.js` instead of `dev_start.js`
Let me know if you agree

**Comment by iqbalgds** [comment]
Not needed anymore - closing.

**Pull request closed without merging**
